### ISSUE TITLE
 What is a license of your code?

### ISSUE THREAD

**Issue by Hiroshiba** [yamachu/julius4seg#6]
MIT? :-)

**Comment by yamachu** [comment]
@Hiroshiba 

Sorry for the late reply.
Yes, _my code_ is provided under the MIT license.
And you need to follow `Julius Japanese Dictation-kit`'s license (https://github.com/julius-speech/dictation-kit/blob/master/LICENSE.txt), in particular section 3 and 3-2 (this application use julius binary and jnas-acoustic model), when you use julius4seg with calling Julius Japanese Dictation-kit.

**Comment by Hiroshiba** [comment]
Thanks a lot!!!!
